config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/forgot', to: 'passwords#forgot'
  post '/reset', to: 'passwords#reset'

  get '/dashboard', to: 'dashboard#show'

  post '/join', to: 'memberships#create'
  delete '/leave', to: 'memberships#destroy'

  resources :users, except: [:new, :create, :destroy, :index] 
  resources :organisations, except: [:index, :show, :new] do
    resources :shifts, only: [:index]
  end

  resources :shifts, except: [:index, :show]
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @user = current_user
    
    if @user.organisation
      @organisation = @user.organisation
      render 'member_show'
    else
      @organisations = Organisation.all.alpha
      # Allow user to create a new organisation if desired
      @organisation = Organisation.new
      render 'non_member_show'
    end
  end
end

app/views/dashboard/_organisation.html.erb
<div class="dash-org-row">
  <p><%= organisation.name %></p>
  <%= button_to "JOIN", join_path, params: { membership: {organisation_id: organisation.id} }, disable_with: "Joining...", class: "btn-link" %>
  <%= link_to "EDIT", edit_organisation_path(organisation) %>
</div>

app/views/dashboard/member_show.html.erb
<div class="flex-center">
  <%= render partial: '/shared/flash_alerts' %>
  <h1 class="page-title"><%= @organisation.name %></h1>
  <div class="flex-two-center dash-cta">
    <%= link_to "View shifts", organisation_shifts_path(@organisation), class: "btn-primary" %>
    <%= link_to "Edit", edit_organisation_path(@organisation), class: "btn-primary" %>
    </div>
  <%= button_to "Leave this organisation", leave_path, method: :delete, params: { membership: {organisation_id: @organisation.id} }, disable_with: "Leaving...", class: "btn-alert-text" %>
</div>

app/views/dashboard/non_member_show.html.erb
<%= render partial: '/shared/flash_alerts' %>
<h1 class="page-title">Join an organisation</h1>
<p class="flex-center">You aren’t a member of any organisation. Join an existing one or create a new one to join.</p>

<div class="flex-two-center dash-member">
  <div class="flex-left">
    <h2>Organisations</h2>
    <div class="scroll-sm">
      <%= render partial: '/dashboard/organisation', collection: @organisations, locals: {user: @user} %>
      <%= no_records_msg(@organisations) %>
    </div>
  </div>
  <div class="flex-right">
    <h2>Create an organisation</h2>
    <%= render partial: '/organisations/form', locals: {organisation: @organisation} %>
  </div>
</div>