config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/forgot', to: 'passwords#forgot'
  post '/reset', to: 'passwords#reset'

  get '/dashboard', to: 'dashboard#show'

  post '/join', to: 'memberships#create'
  delete '/leave', to: 'memberships#destroy'

  resources :users, except: [:new, :create, :destroy, :index] 
  resources :organisations, except: [:index, :show, :new] do
    resources :shifts, only: [:index]
  end

  resources :shifts, except: [:index, :show]
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :organisation, optional: true
  has_many :shifts

  # allow_blank: true so length validation runs only if password is present
  # Allows user to update their details (email, name) without having to update their password at same time
  validates :password, length: { minimum: 6, allow_blank: true }
  validates :name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  # Use gem Email Validator in strict mode to validate email addresses
  validates :email, email: {mode: :strict, require_fqdn: true}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  before_action :redirect_if_logged_in, except: [:edit, :update, :show]
  before_action :set_user, only: [:show, :edit, :update]

  # Users can create accounts and view + edit their account details
  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      flash[:alert] = "Unable to create account. Please try again."
      redirect_to signup_path
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = current_user
  end
end

app/views/users/edit.html.erb
<h1 class="page-title">Edit account</h1>
<div class="center-form">
<%= form_with model: @user, url: user_path(@user), local: true do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <%= f.label :email %><br>
  <%= f.email_field :email %><br>

  <h2 class="heading-3">Password reset (optional)</h2>
  <%= f.label :password %><br>
  <%= f.password_field :password, placeholder: "Set new password" %><br>

  <%= f.label :password_confirmation %><br>
  <p class="auth-helper">(6 characters minimum)</p>
  <%= f.password_field :password_confirmation, placeholder: "Confirm new password" %><br>

  <%= f.submit "Save", class: "btn-primary" %>
<% end %>
</div>

app/views/users/new.html.erb
<div class="auth-container">
  <p class="auth-site-name">Adnat<p>  
  <div class="auth-form">
    <h1>Sign Up</h1>
    <%= form_with model: @user, url: signup_path do |f| %>
      <%= f.label :name %><br>
      <%= f.text_field :name %><br>

      <%= f.label :email %><br>
      <%= f.email_field :email %><br>

      <%= f.label :password %><br>
      <%= f.password_field :password %><br>

      <%= f.label :password_confirmation %><br>
      <p class="auth-helper">(6 characters minimum)</p>
      <%= f.password_field :password_confirmation %><br>

      <%= f.submit "Sign Up", class: "btn-cta" %>
    <% end %>
    <%= render partial: '/shared/flash_alerts' %>
  </div>
  <p>Already a member? <strong><%= link_to 'Login', login_path, class: "link-inverse" %></strong></p>
</div>

app/views/users/show.html.erb
<h1 class="page-title">Account details</h1>
<div class="flex-center">
  <div class="user-card">
    <p class="emphasis">Name</p>
    <p><%= @user.name %></p>
    <p class="emphasis">Email</p>
    <p><%= @user.email %></p>
  </div>
  <%= link_to "Edit", edit_user_path(@user), class: "btn-primary" %>
</div>