config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/forgot', to: 'passwords#forgot'
  post '/reset', to: 'passwords#reset'

  get '/dashboard', to: 'dashboard#show'

  post '/join', to: 'memberships#create'
  delete '/leave', to: 'memberships#destroy'

  resources :users, except: [:new, :create, :destroy, :index] 
  resources :organisations, except: [:index, :show, :new] do
    resources :shifts, only: [:index]
  end

  resources :shifts, except: [:index, :show]
end

app/models/shift.rb
class Shift < ApplicationRecord
  attr_accessor :date, :start_time, :finish_time, :overnight
  belongs_to :user
  
  before_validation :set_start_datetime, :set_finish_time
  validates :break_length, numericality: { only_integer: true }
  validate :ensure_valid_start_time
  validate :ensure_valid_finish_time
  validate :ensure_valid_date
  validates_datetime :start
  validates_datetime :finish
  validates_date :start, on_or_before: :today

  scope :newest, -> {order(start: :desc)}
  
  def self.filter_by_user_name(q)
    includes(:user).where("name ILIKE ?", "%#{q}%")
  end

  def overnight
   self[:start].day < self[:finish].day
  end

  private 
  def set_start_datetime
    self[:start] = date + " " + start_time
  end

  def set_finish_time
    if finish_time < start_time
      # Increase date by one for overnight shift
      next_day = Date.parse(date) + 1
      self[:finish] = next_day.to_s + " " + finish_time
    else
      self[:finish] = date + " " + finish_time
    end
  end

  def ensure_valid_date
    d, m, y = date.split '-'
    Date.valid_date?(y.to_i, m.to_i, d.to_i)
  end

  def ensure_valid_start_time
    if !start_time.match(/^\d{1,2}:\d{1,2}(:\d{1,2})?/)
      errors.add(:start_time, "must be valid time")
    end
  end

  def ensure_valid_finish_time
    if !finish_time.match(/^\d{1,2}:\d{1,2}(:\d{1,2})?/)
      errors.add(:finish_time, "must be valid time")
    end
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_user, only: [:new, :create]
  before_action :set_shift, only: [:edit, :update, :destroy]
  before_action :set_organisation, :redirect_if_not_authorized, only: [:index, :edit, :update, :destroy]

  # Index only used for nested route - organisation/:id/shifts
  def index
    org_id = params[:organisation_id]
    @shifts = Shift.includes(:user).where(users: {organisation_id: org_id}).newest
    if params[:q]
      @shifts = @shifts.filter_by_user_name(params[:q])
    end
  end

  # Only allow users who have an org to add a shift
  def new
    if @user.organisation
      @shift = Shift.new
    else
      redirect_to dashboard_path
    end
  end

  # Only allow users who have an org to add a shift
  def create
    if @user.organisation
      @shift = @user.shifts.build(shift_params)
      if @shift.save
        redirect_to organisation_shifts_path(@user.organisation)
      else
        render :new
      end
    else
      redirect_to dashboard_path
    end
  end

  def edit
  end

  # Only allow users to edit shifts at their org
  def update
    if @shift.update(shift_params)
      redirect_to organisation_shifts_path(@organisation)
    else
      render :edit
    end
  end

  def destroy
    @shift.destroy
    redirect_to organisation_shifts_path(@organisation)
  end

  private
  def shift_params
    params.require(:shift).permit(:date, :start_time, :finish_time, :break_length)
  end

  def set_user
    @user = current_user
  end

  def set_shift
    @shift = Shift.find_by_id(params[:id])
  end

  def redirect_if_not_authorized
    # Make sure current user is a member of the organisation where shift took place
    if !@organisation || current_user.organisation_id != @organisation.id
      flash[:alert] = "Invalid path"
      redirect_to dashboard_path
    end
  end

  def set_organisation
    # If accessing via nested route (shifts index view), verify org based on id in route params
    if params[:organisation_id]
      @organisation = Organisation.find_by_id(params[:organisation_id])
    else
      @organisation = @shift.user.organisation
    end
  end
end

app/helpers/shifts_helper.rb
module ShiftsHelper

  def display_date(shift)
    shift.start.strftime("%m/%d/%Y")
  end

  def display_time(datetime_obj)
    datetime_obj.strftime("%l:%M %p")
  end

  def form_date(shift)
    shift.try(:start).try(:to_date)
  end

  def form_start_time(shift)
    shift.try(:start).try(:strftime, "%T.%L")
  end

  def form_finish_time(shift)
    shift.try(:finish).try(:strftime, "%T.%L")
  end

  def hours_worked(shift)
    break_hours = shift.break_length/60.to_f
    TimeDifference.between(shift.start, shift.finish).in_hours - break_hours
  end

  def shift_cost(shift, organisation)
    cost = hours_worked(shift) * organisation.hourly_rate
    number_to_currency(cost)
  end
end

app/views/shifts/_form.html.erb
<%= render partial: '/shared/validation_errors', locals: {object: shift} %>

<%= form_with model: shift, local: true do |f| %>
  <%= f.label :date %><br>
  <%= f.date_field :date, value: form_date(shift) %><br>
  <%= f.label :start_time %><br>
  <%= f.time_field :start_time, value: form_start_time(shift) %><br>
  <%= f.label :finish_time %><br>
  <%= f.time_field :finish_time, value: form_finish_time(shift) %><br>
  <%= f.label :break_length %> (minutes)<br>
  <%= f.number_field :break_length %><br>
  <%= f.submit "Save", class: "btn-primary" %>
<% end %>

app/views/shifts/_shift.html.erb
<tr class="table-row">
  <td><%= shift.user.name %></td>
  <td>
    <%= display_date(shift) %>
    <% if shift.overnight %>
      <%= fa_icon "moon-o", title: "Overnight", id: "moon-icon", class: "icon-m" %>
    <% end %>
  </td>
  <td><%= display_time(shift.start) %></td>
  <td><%= display_time(shift.finish) %></td>
  <td><%= shift.break_length %></td>
  <td><%= number_with_precision(hours_worked(shift), precision: 2) %></td>
  <td><%= shift_cost(shift, organisation) %></td>
  <td>
    <%= link_to edit_shift_path(shift) do %>
      <%= fa_icon "edit", title: "Edit", class: "icon-m" %>
    <% end %>
  </td>
  <td>
    <%= button_to shift_path(shift), method: :delete, data: { confirm: "Confirm delete shift" }, class: "btn-link" do %>
      <%= fa_icon "trash", title: "Delete", id: "trash-icon", class: "icon-m" %>
    <% end %>
  </td>
</tr>

app/views/shifts/edit.html.erb
<h1 class="page-title">Editing shift</h1>

<div class="flex-center">
  <%= render partial: 'form', locals: {shift: @shift} %>
</div>

app/views/shifts/index.html.erb
<div class="cw-container">
  <h1 class="page-title"><%= @organisation.name %></h1>
  <h2 class="sub-title">Shifts</h2>

  <div class="flex-two-split">
    <div>
    <%= form_with url: organisation_shifts_path(@organisation), method: :get, local: true, class: "search-bar" do |f| %>
      <%= f.label :q, "Filter by employee name" %>
      <%= f.text_field :q, id: :q %> 
      <%= f.submit "Apply" %>
    <% end %>
    <%= link_to "View all", organisation_shifts_path(@organisation) %>
    </div>
    <div>
      <%= link_to "Add your shift", new_shift_path, class: "btn-primary" %>
    </div>
  </div>
  <div class="scroll">
    <table class="full-width">
      <thead>
        <tr>
          <th class="emphasis">Employee Name</th>
          <th class="emphasis">Shift Date</th>
          <th class="emphasis">Start Time</th>
          <th class="emphasis">Finish Time</th>
          <th class="emphasis">Break length<br><span>(total mins)<span></th>
          <th class="emphasis">Hours worked</th>
          <th class="emphasis">Shift cost</th>
          <th class="emphasis">Edit</th>
          <th class="emphasis">Delete</th>
        <tr>
      </thead>
      <tbody>
        <%= render partial: 'shift', collection: @shifts, locals: {shift: @shift, organisation: @organisation} %>
        <%= no_table_records_msg(@shifts) %>
      </tbody>
    </table>
  </div>
  <div class="table-helper">
    <%= fa_icon "moon-o", title: "Overnight", id: "moon-icon", class: "icon-m" %> Indicates overnight shift</p>
  </div>
</div>

app/views/shifts/new.html.erb
<h1 class="page-title">Add your shift</h1>
<h2 class="sub-title"><%= @user.name %></h2>

<div class="flex-center">
  <%= render partial: 'form', locals: {shift: @shift} %>
</div>