config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/forgot', to: 'passwords#forgot'
  post '/reset', to: 'passwords#reset'

  get '/dashboard', to: 'dashboard#show'

  post '/join', to: 'memberships#create'
  delete '/leave', to: 'memberships#destroy'

  resources :users, except: [:new, :create, :destroy, :index] 
  resources :organisations, except: [:index, :show, :new] do
    resources :shifts, only: [:index]
  end

  resources :shifts, except: [:index, :show]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Adnat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;500;700&display=swap" rel="stylesheet">
  </head>

  <body>
    <% if current_user %>
      <nav class="navbar cw-container">
          <div class="nav-home">
            <%= link_to 'Adnat', dashboard_path %>
          </div>
          <ul class="nav-links">
            <li>
              <%= link_to current_user.name, user_path(current_user) %>
            </li>
            <li>
              <%= link_to 'Logout', logout_path, method: 'delete' %>
            </li>
          </ul>
      </nav>
      <hr class="nav-hr">
    <% end %>
    <%= yield %>
  </body>
</html>